player_speed_original = 3
sped = player_speed_original
keys_pressed = 0
body = instance_create_depth(x,y,-2,obj_player_body)
grabber = instance_create_depth(x,y,-3,obj_player_grabber)
wheels = instance_create_depth(x,y,-1,obj_player_wheels)
global.loudout = [[obj_gun_auto, obj_bullet_bleeding], [ obj_gun_sprayer, obj_bullet_arial], [obj_gun_sinper, obj_bullet_homing]]
global.selected_gun = 0
gun = instance_create_depth(obj_player.x,obj_player.y,depth-1,global.loudout[global.selected_gun][0])
gun.selected = true
gun.bullet = global.loudout[global.selected_gun][1]
maxhp = 25
hp = maxhp
dead = false
dash_cooldown = false
bleed = 10
freezing = false
global.new_game = true